apps/contact/urls.py
from django.urls import path

from .views import get_in_touch


urlpatterns = [
    path('contact/', get_in_touch, name="contact"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.article.urls')),
    path('', include('apps.account.urls')),
    path('', include('apps.contact.urls')),

    # media
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

handler404 = "config.errors.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

apps/article/models.py
from django.db import models

from django.template.defaultfilters import slugify  # new
from django.urls import reverse

from apps.account.models import Account


class Category(models.Model):
    title = models.CharField(max_length=225, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=225)
    
    def get_absolute_url(self):
        return reverse("category", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=225, null=True, blank=True)

    def __str__(self):
        return self.title   


class Article(models.Model):
    title = models.CharField(max_length=225, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=225)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)  # OneToMany
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    image_1 = models.ImageField(upload_to='Article/', null=True, blank=True)
    image_2 = models.ImageField(upload_to='Article/', null=True, blank=True)
    image_3 = models.ImageField(upload_to='Article/', null=True, blank=True)
    for_banner = models.BooleanField(default=False, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
        
    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
            
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=225, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

apps/contact/models.py
from django.db import models


class GetInTouch(models.Model):
    name = models.CharField(max_length=225, null=True, blank=True)
    phone = models.CharField(max_length=225, null=True, blank=True)
    email = models.EmailField(null=True, blank=True, unique=True)
    message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

apps/contact/forms.py
from django import forms

from .models import GetInTouch


class GetInTouchForm(forms.ModelForm):
    class Meta:
        model = GetInTouch
        fields = "__all__"
        execute = ["created_at"]
    
    def __init__(self, *args, **kwargs):
        super(GetInTouchForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            

apps/contact/views.py
from django.shortcuts import render, redirect

from .forms import GetInTouchForm


def get_in_touch(request):
    form = GetInTouchForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        
        return redirect("contact")
    
    return render(request, "contact.html", {"form": form})

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
      <title>Balita</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,%20400,700" rel="stylesheet">
      <link rel="stylesheet" href="{% static '' %}css/bootstrap.css">
      <link rel="stylesheet" href="{% static '' %}css/animate.css">
      <link rel="stylesheet" href="{% static '' %}css/owl.carousel.min.css">
      <link rel="stylesheet" href="{% static '' %}fonts/ionicons/css/ionicons.min.css">
      <link rel="stylesheet" href="{% static '' %}fonts/fontawesome/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static '' %}fonts/flaticon/font/flaticon.css">
      <link rel="stylesheet" href="{% static '' %}css/style.css">
</head>

<body>
      <header role="banner">
            <div class="top-bar">
                  <div class="container">
                        <div class="row">
                              <div class="col-9 social">
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="https://www.instagram.com/turdali.hasanboyev.07/"><span class="fa fa-instagram"></span></a>
                                    <a href="#"><span class="fa fa-youtube-play"></span></a>
                                    <a href="#"><span class="fa fa-vimeo"></span></a>
                                    <a href="#"><span class="fa fa-snapchat"></span></a>
                                    {% if request.user.is_authenticated %}
                                    <a href="{% url 'logout' %}">Logout</a>
                                    {% else %}
                                    <a href="{% url 'login' %}">Login</a>|<a href="{% url 'register' %}">Register</a>
                                    {% endif %}

                              </div>
                              <div class="col-3 search-top">
                                    <form action="#" class="search-top-form">
                                          <span class="icon fa fa-search"></span>
                                          <input type="text" id="s" placeholder="Type keyword to search...">
                                    </form>
                              </div>
                        </div>
                  </div>
            </div>
            <div class="container logo-wrap">
                  <div class="row pt-5">
                        <div class="col-12 text-center">
                              <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu"
                                    role="button" aria-expanded="false" aria-controls="navbarMenu"><span
                                          class="burger-lines"></span></a>
                              <h1 class="site-logo"><a href="/">Balita</a></h1>
                        </div>
                  </div>
            </div>
            <nav class="navbar navbar-expand-md  navbar-light bg-light">
                  <div class="container">
                        <div class="collapse navbar-collapse" id="navbarMenu">
                              <ul class="navbar-nav mx-auto">
                                    <li class="nav-item">
                                          <a class="nav-link active" href="/">Home</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                          <a class="nav-link dropdown-toggle" href="#" id="dropdown04"
                                                data-toggle="dropdown" aria-haspopup="true"
                                                aria-expanded="false">Categories</a>
                                          <div class="dropdown-menu" aria-labelledby="dropdown04">
                                                {% for cat in categories %}
                                                <a class="dropdown-item" href="{{ cat.get_absolute_url }}">{{cat}} </a>
                                                {% endfor %}
                                          </div>
                                    </li>
                                    <li class="nav-item">
                                          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                                    </li>
                              </ul>
                        </div>
                  </div>
            </nav>
      </header>

      {% block content %}

      {% endblock %}

      <footer class="site-footer">
            <div class="container">
                  <div class="row mb-5">
                        <div class="col-md-4">
                              <h3>Paragraph</h3>
                              <p>
                                    <img src="{% static '' %}images/img_1.jpg" alt="Image placeholder"
                                          class="img-fluid">
                              </p>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi, accusantium optio unde
                                    perferendis eum illum voluptatibus dolore tempora, consequatur minus asperiores
                                    temporibus reprehenderit.</p>
                        </div>
                        <div class="col-md-6 ml-auto">
                              <div class="row">
                                    <div class="col-md-7">
                                          <h3>Latest Post</h3>
                                          <div class="post-entry-sidebar">
                                                <ul>
                                                      {% for article in articles %}
                                                      <li>
                                                            <a href>
                                                                  <img src="{{ article.image_1.url }}"
                                                                        alt="Image placeholder" class="mr-4">
                                                                  <div class="text">
                                                                        <h4>{{ article.description }}</h4>
                                                                        <div class="post-meta">
                                                                              <span class="mr-2">{{ article.created_at|date }}</span>
                                                                              &bullet;
                                                                              <span class="ml-2"><span
                                                                                          class="fa fa-comments"></span>
                                                                                    {{ article.comment_set.count }}</span>
                                                                        </div>
                                                                  </div>
                                                            </a>
                                                      </li>
                                                      {% endfor %}
                                                </ul>
                                          </div>
                                    </div>
                                    <div class="col-md-1"></div>
                                    <div class="col-md-4">

                                          <div class="mb-5">
                                                <h3>Social</h3>
                                                <ul class="list-unstyled footer-social">
                                                      <li><a href="#"><span class="fa fa-twitter"></span> Twitter</a>
                                                      </li>
                                                      <li><a href="#"><span class="fa fa-facebook"></span> Facebook</a>
                                                      </li>
                                                      <li><a href="https://www.instagram.com/turdali.hasanboyev.07/"><span
                                                                        class="fa fa-instagram"></span>
                                                                  Instagram</a></li>
                                                      <li><a href="#"><span class="fa fa-vimeo"></span> Vimeo</a></li>
                                                      <li><a href="#"><span class="fa fa-youtube-play"></span>
                                                                  Youtube</a></li>
                                                      <li><a href="#"><span class="fa fa-snapchat"></span> Snapshot</a>
                                                      </li>
                                                </ul>
                                          </div>
                                    </div>
                              </div>
                        </div>
                  </div>
                  <div class="row">
                        <div class="col-md-12">

                              Copyright &copy;
                              <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                              template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                    href="https://t.me/vectorzafar/" target="_blank">EduVector</a>

                        </div>
                  </div>
            </div>
      </footer>

      <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
                  <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
                  <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                        stroke="#f4b214" />
            </svg></div>
      <script src="{% static '' %}js/anime-404.js"></script>
      <script src="{% static '' %}js/jquery-3.2.1.min.js"></script>
      <script src="{% static '' %}js/jquery-migrate-3.0.0.js"></script>
      <script src="{% static '' %}js/popper.min.js"></script>
      <script src="{% static '' %}js/bootstrap.min.js"></script>
      <script src="{% static '' %}js/owl.carousel.min.js"></script>
      <script src="{% static '' %}js/jquery.waypoints.min.js"></script>
      <script src="{% static '' %}js/jquery.stellar.min.js"></script>
      <script src="{% static '' %}js/main.js"></script>

      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>

</body>

</html>

templates/blog-single.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

      <section class="site-section py-lg">
            <div class="container">
                  <div class="row blog-entries">
                        <div class="col-md-12 col-lg-8 main-content">
                              <h1 class="mb-4">{{ article.title }}</h1>
                              <div class="post-meta">
                                    <span class="category">{{ article.category.title }}</span>
                                    <span class="mr-2">{{ article.created_at|date }} </span> &bullet;
                                    <span class="ml-2"><span class="fa fa-comments"></span> {{ article.comment_set.count }}</span>
                              </div>
                              <div class="post-content-body">
                                    <p>{{ article.description }}</p>
                                    <div class="row mb-5">
                                          <div class="col-md-12 mb-4 element-animate">
                                                <img src="{{ article.image_1.url }}" alt="Image placeholder" class="img-fluid">
                                          </div>
                                          <div class="col-md-6 mb-4 element-animate">
                                                <img src="{{ article.image_2.url }}" alt="Image placeholder" class="img-fluid">
                                          </div>
                                          <div class="col-md-6 mb-4 element-animate">
                                                <img src="{{ article.image_3.url }}" alt="Image placeholder" class="img-fluid">
                                          </div>
                                    </div>
                              </div>
                              <div class="pt-5">
                                     Tags: 
                                     {% for tag in article.tags.all %}
                                          <a href="/?tag={{ tag.title }}">#{{ tag.title }}</a>
                                     {% endfor %}
                              </div>
                              <div class="pt-5">
                                    <h3 class="mb-5">{{ article.comment_set.count }} Comments</h3>
                                    <ul class="comment-list">
                                          {% for comment in comments %}
                                          <li class="comment">
                                                <div class="vcard">
                                                      {% if comment.user.avatar %}
                                                      <img src="{{comment.user.avatar.url}}" alt="Image placeholder">
                                                      {% else %}
                                                      <img src="{% static '' %}images/default_user.png" alt="Image placeholder">
                                                      {% endif %}
                                                </div>
                                                <div class="comment-body">
                                                      <h3>{{ comment.name }}</h3>
                                                      <div class="meta">{{ comment.created_at }}</div>
                                                      <p>{{ comment.comment }}</p>
                                                      <p><a href="{% url 'detail' article.slug %}" class="reply">Reply</a></p>
                                                </div>
                                          </li>
                                          {% endfor %}
                                    </ul>

                                    <div class="comment-form-wrap pt-5">
                                          <h3 class="mb-5">Leave a comment</h3>
                                          <form action="#comment" class="p-5 bg-light" method="post">

                                                {% csrf_token %}
                                                
                                                <div class="form-group">
                                                      <label for="name">Name *</label>
                                                      <input type="text" class="form-control" id="name" name="name">
                                                </div>
                                                <div class="form-group">
                                                      <label for="email">Email *</label>
                                                      <input type="email" class="form-control" id="email" name="email">
                                                </div>
                                                <div class="form-group">
                                                      <label for="comment">Message</label>
                                                      <textarea id="comment" name="comment" cols="30" rows="10"
                                                            class="form-control"></textarea>
                                                </div>
                                                <div class="form-group">
                                                      <input type="submit" value="Post Comment" class="btn btn-primary">
                                                </div>
                                          </form>
                                    </div>
                              </div>
                        </div>

                        {% include 'rside.html' %}

                  </div>
            </div>
      </section>
      <section class="py-5">
            <div class="container">
                  <div class="row">
                        <div class="col-md-12">
                              <h2 class="mb-3 ">Related Post</h2>
                        </div>
                  </div>
                  <div class="row">
                        {% for article in articles %}
                              <div class="col-md-6 col-lg-4">
                                    <a href="{{ article.get_absolute_url }}" class="a-block d-flex align-items-center height-md"
                                          style="background-image: url({{ article.image_1.url }});">
                                          <div class="text">
                                                <div class="post-meta">
                                                      <span class="category">{{ article.category }}</span>
                                                      <span class="mr-2">{{ article.created_at|date }} </span> &bullet;
                                                      <span class="ml-2"><span class="fa fa-comments"></span> {{ article.comment_set.count }}</span>
                                                </div>
                                                <h3>{{ article.title|slice:"0:30" }}...</h3>
                                          </div>
                                    </a>
                              </div>
                        {% endfor %}
                  </div>
            </div>
      </section>

{% endblock %}

templates/category.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="site-section">
      <div class="container">
            <div class="row mb-4">
                  <div class="col-md-6">
                        <h2 class="mb-4">Category: {{ category.title }}</h2>
                  </div>
            </div>
            <div class="row blog-entries">
                  <div class="col-md-12 col-lg-8 main-content">
                        <div class="row mb-5 mt-5">
                              <div class="col-md-12">
                                    {% for article in articles %}
                                    <div class="post-entry-horzontal">
                                          <a href="{% url 'detail' article.slug %}">
                                                <!-- {{ article.get_absolute_url }} -->
                                                <div class="image element-animate" data-animate-effect="fadeIn"
                                                      style="background-image: url({{ article.image_1.url}});"></div>
                                                <span class="text">
                                                      <div class="post-meta">
                                                            <span class="category">{{ category.title }}</span>
                                                            <span class="mr-2">{{ article.created_at|date }} </span>
                                                            &bullet;
                                                            <span class="ml-2"><span class="fa fa-comments"></span> {{ article.comment_set.count }}</span>
                                                      </div>
                                                      <h2>{{ article.title }}
                                                      </h2>
                                                </span>
                                          </a>
                                    </div>
                                    {% endfor %}
                              </div>
                        </div>

                        {% include 'paginator.html' %}

                  </div>

                  {% include 'rside.html' %}

            </div>
      </div>
</section>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

      <section class="site-section">
            <div class="container">
                  <div class="row mb-4">
                        <div class="col-md-6">
                              <h1>Contact</h1>
                        </div>
                  </div>
                  <div class="row blog-entries">
                        <div class="col-md-12 col-lg-8 main-content">
                              <form method="post">

                                    {% csrf_token %}

                                    {{ form.as_p }}
                                    
                                     <div class="row">
                                          <div class="col-md-6 form-group">
                                                <input type="submit" value="Send Message" class="btn btn-primary">
                                    </div>
                                    </div>
                              </form>
                        </div>

                        {% include 'rside.html' %}

                  </div>
            </div>
      </section>

{% endblock %}

templates/rside.html
{% load static %}

<div class="col-md-12 col-lg-4 sidebar">
      <div class="sidebar-box search-form-wrap">
            <form action="#" class="search-form">
                  <div class="form-group">
                        <span class="icon fa fa-search"></span>
                        <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
                  </div>
            </form>
      </div>
      {% if request.user.is_authenticated %}
      <div class="sidebar-box">
            <div class="bio text-center">
                  {% if request.user.avatar %}
                  <img src="{{ request.user.avatar.url }}" alt="Image Placeholder" class="img-fluid">
                  {% else %}
                  <img src="{% static '' %}images/default_user.png" alt="Image placeholder" class="img-fluid">
                  {% endif %}
                  <div class="bio-body">
                        <h2>{{ request.user.get_full_name }}</h2>
                        <p>{{ request.user.bio }}</p>
                        <p><a href="#" class="btn btn-primary btn-sm">Read my bio</a></p>
                        <p class="social">
                              <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
                              <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
                              <a href="https://www.instagram.com/turdali.hasanboyev.07/" class="p-2"><span
                                          class="fa fa-instagram"></span></a>
                              <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
                        </p>
                  </div>
            </div>
      </div>
      {% else %}
      <div class="sidebar-box">
            <div class="bio text-center">
                  <img src="{% static 'images/person_1.jpg' %}" alt="Image Placeholder" class="img-fluid">
                  <div class="bio-body">
                        <h2>Meagan Smith</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                              Exercitationem facilis sunt repellendus excepturi beatae porro
                              debitis voluptate nulla quo veniam fuga sit molestias minus.</p>
                        <p><a href="#" class="btn btn-primary btn-sm">Read my bio</a></p>
                        <p class="social">
                              <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
                              <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
                              <a href="https://instagram.com/turdali.hasanboyev.07/" class="p-2"><span class="fa fa-instagram"></span></a>
                              <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
                        </p>
                  </div>
            </div>
      </div>
      {% endif %}

      <div class="sidebar-box">
            <h3 class="heading">Popular Posts</h3>
            <div class="post-entry-sidebar">
                  <ul>
                        {% for article in last_articles %}
                        <li>
                              <a href="{{ article.get_absolute_url }}">
                                    <img src="{{ article.image_1.url }}" alt="Image placeholder" class="mr-4">
                                    <div class="text">
                                          <h4>{{ article.title|slice:"0:35" }}</h4>
                                          <div class="post-meta">
                                                <span class="mr-2">{{ article.created_at|date }} </span>
                                                &bullet;
                                                <span class="ml-2"><span class="fa fa-comments"></span>{{ article.comment_set.count }}</span>
                                          </div>
                                    </div>
                              </a>
                        </li>
                        {% endfor %}
                  </ul>
            </div>
      </div>

      <div class="sidebar-box">
            <h3 class="heading">Categories</h3>
            <ul class="categories">
                  {% for cat in categories %}
                  <li><a href="{% url 'category' cat.slug %}">{{ cat.title }} <span>({{ cat.article_set.count }})</span></a></li>
                  {% endfor %}
            </ul>
      </div>

      <div class="sidebar-box">
            <h3 class="heading">Tags</h3>
            <ul class="tags">
                  {% for tag in tags %}
                  <li><a href="?tag={{ tag }}">{{ tag }}</a></li>
                  {% endfor %}
            </ul>
      </div>
</div>